import { Commission, MonthlyPerformance } from '@/types/commission'

export const COMMISSIONS: Commission[] = [
  {
    id: 1,
    name: 'John Doe',
    policyId: 101,
    type: 'Life',
    commission: 4500,
    status: 'Paid',
    paidOn: new Date('2025-07-05'),
  },
  {
    id: 2,
    name: 'Jane Smith',
    policyId: 102,
    type: 'Health',
    commission: 3900,
    status: 'Pending',
    paidOn: new Date('2025-07-12'),
  },
  {
    id: 3,
    name: 'Carlos Reyes',
    policyId: 103,
    type: 'Business',
    commission: 7200,
    status: 'Clawback',
    paidOn: new Date('2025-07-15'),
  },
  {
    id: 4,
    name: 'Angela Cruz',
    policyId: 104,
    type: 'Travel',
    commission: 1800,
    status: 'Paid',
    paidOn: new Date('2025-07-18'),
  },
  {
    id: 5,
    name: 'Robert Chan',
    policyId: 105,
    type: 'Life',
    commission: 5000,
    status: 'Pending',
    paidOn: new Date('2025-07-20'),
  },
  {
    id: 6,
    name: 'Mia Lim',
    policyId: 106,
    type: 'CPTL',
    commission: 8800,
    status: 'Paid',
    paidOn: new Date('2025-07-22'),
  },
  {
    id: 7,
    name: 'Liam Tan',
    policyId: 107,
    type: 'Health',
    commission: 4100,
    status: 'Pending',
    paidOn: new Date('2025-07-25'),
  },
  {
    id: 8,
    name: 'Sophia Torres',
    policyId: 108,
    type: 'Business',
    commission: 9600,
    status: 'Clawback',
    paidOn: new Date('2025-07-28'),
  },
  {
    id: 9,
    name: 'Ethan Ramos',
    policyId: 109,
    type: 'Travel',
    commission: 2300,
    status: 'Paid',
    paidOn: new Date('2025-08-01'),
  },
  {
    id: 10,
    name: 'Isabella Perez',
    policyId: 110,
    type: 'Life',
    commission: 5100,
    status: 'Paid',
    paidOn: new Date('2025-08-03'),
  },
  {
    id: 11,
    name: 'Noah Dizon',
    policyId: 111,
    type: 'Health',
    commission: 3700,
    status: 'Pending',
    paidOn: new Date('2025-08-05'),
  },
  {
    id: 12,
    name: 'Ava Mendoza',
    policyId: 112,
    type: 'CPTL',
    commission: 8100,
    status: 'Paid',
    paidOn: new Date('2025-08-07'),
  },
]

export const monthlyPerformanceData: MonthlyPerformance[] = [
  { month: 'Jan', commission: 4500 },
  { month: 'Feb', commission: 4200 },
  { month: 'Mar', commission: 5500 },
  { month: 'Apr', commission: 5100 },
  { month: 'May', commission: 6200 },
  { month: 'Jun', commission: 7100 },
  { month: 'Jul', commission: 6800 },
]
